version: "3"
services:

  registrator:
    image: gliderlabs/registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -internal consul://consul:8500
    depends_on:
      - consul
    links:
      - consul

  consul:
    image: consul
    command: "agent -server -bootstrap -ui -client=0.0.0.0 -bind='{{ GetPrivateIP }}'"

  message-old:
    build: messagev1/
    deploy:
      replicas: 1
    environment:
      - APIPORT=80
      - SERVICE_NAME=service-v1
    ports:
      - 80
    links:
      - haproxy

    volumes:
      - "./messagev1:/app"

  message-new:
    build: messagev2/
    deploy:
      replicas: 1
    environment:
      - APIPORT=80
      - SERVICE_NAME=service-v2
    ports:
      - 80
    links:
      - haproxy

    volumes:
      - "./messagev2:/app"
  credit:
    build: credit/
    ports:
      - "9017:9017"
    links:
      - mongodb_credit
      - replica_credit
      - redis
    depends_on:
      - mongodb_credit
      - replica_credit
      - redis
    volumes:
      - "./credit:/app"
  messageapp:
    image: cabify/backend-bootcamp-messageapp
    ports:
      - "3000:3000"

  mongodb_credit:
    image: mongo
    command:
      - '--logpath'
      - '/var/log/mongodb/main_credit.log'
    volumes:
      - ./credit/data/db:/credit/data/db
    ports:
      - 27017:27017
  replica_credit:
    image: mongo
    command:
      - '--logpath'
      - '/var/log/mongodb/replica_credit.log'
    volumes:
      - ./credit/data/replica:/credit/data/replica
    ports:
      - 27018:27017

  mongodb_message:
    image: mongo
    command:
      - '--logpath'
      - '/var/log/mongodb/main_message.log'
    volumes:
      - ./message/data/db:/message/data/db
    ports:
      - 27027:27017
  replica_message:
    image: mongo
    command:
      - '--logpath'
      - '/var/log/mongodb/replica_message.log'
    volumes:
      - ./message/data/replica:/message/data/replica
    ports:
      - 27028:27017

  redis:
    image: redis
    ports:
      - 6379:6379

  haproxy:
    image: haproxy:1.8-alpine
    ports:
      - 9000:9000
    links:
      - registrator
    depends_on:
      - registrator
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
