version: "3"
services:
  # sever:
  #   build: .
  #   ports:
  #     - "9003:9003"
  #   depends_on:
  #     - mongodb
  #     - mongodbbackup
  #     - cache
  messageapp:
    image: cabify/backend-bootcamp-messageapp
    ports:
      - "3000:3000"
  mongodb:
    image: mongo
    volumes:
      - ./data/db1:/data/db1
    ports:
      - 27017:27017
    command:
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
  mongodbbackup:
    image: mongo
    volumes:
      - ./data/db2:/data/db2
    ports:
      - 27018:27017
    command:
      - '--logpath'
      - '/var/log/mongodb/mongodBackup.log'

  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
