version: "3"
services:
  message1:
    build: message/
    restart: always
    environment:
      - APIPORT=9007
    # ports:
    #   - "9007:9007"
    links:
      - messageapp
      - mongodb_message
      - replica_message
      - redis
    depends_on:
      - messageapp
      - mongodb_message
      - replica_message
      - redis
    volumes:
      - "./message:/app"
  message2:
    build: message/
    restart: always
    environment:
      - APIPORT=9008
    # ports:
    #   - "9008:9007"
    links:
      - messageapp
      - mongodb_message
      - replica_message
      - redis
    depends_on:
      - messageapp
      - mongodb_message
      - replica_message
      - redis
    volumes:
      - "./message:/app"
  message3:
    build: message/
    restart: always
    environment:
      - APIPORT=9009
    # ports:
    #   - "9009:9007"
    links:
      - messageapp
      - mongodb_message
      - replica_message
      - redis
    depends_on:
      - messageapp
      - mongodb_message
      - replica_message
      - redis
    volumes:
      - "./message:/app"
  credit:
    build: credit/
    restart: always
    ports:
      - "9017:9017"
    links:
      - mongodb_credit
      - replica_credit
      - redis
    depends_on:
      - mongodb_credit
      - replica_credit
      - redis
    volumes:
      - "./credit:/app"
  messageapp:
    image: cabify/backend-bootcamp-messageapp
    ports:
      - "3000:3000"

  mongodb_credit:
    image: mongo
    command:
      - '--logpath'
      - '/var/log/mongodb/main_credit.log'
    volumes:
      - ./credit/data/db:/credit/data/db
    ports:
      - 27017:27017
  replica_credit:
    image: mongo
    command:
      - '--logpath'
      - '/var/log/mongodb/replica_credit.log'
    volumes:
      - ./credit/data/replica:/credit/data/replica
    ports:
      - 27018:27017

  mongodb_message:
    image: mongo
    command:
      - '--logpath'
      - '/var/log/mongodb/main_message.log'
    volumes:
      - ./message/data/db:/message/data/db
    ports:
      - 27027:27017
  replica_message:
    image: mongo
    command:
      - '--logpath'
      - '/var/log/mongodb/replica_message.log'
    volumes:
      - ./message/data/replica:/message/data/replica
    ports:
      - 27028:27017

  redis:
    image: redis
    ports:
      - 6379:6379

  haproxy:
    build: ./haproxy
    ports:
      - 9000:9000
    depends_on:
      - message1
      - message2
      - message3
