version: "3"
services:

  # messageservice:
  #   build: messageMicroservice/
  #   ports:
  #     - "9003:9003"
  #   links:
  #     - messageapp
  #     - main_message
  #     - replica_message
  #     - cache
  #     - creditservice
  #   depends_on:
  #     - messageapp
  #     - main_message
  #     - replica_message
  #     - cache

  # creditservice:
  #   build: creditMicroservice/
  #   ports:
  #     - "9017:9017"
  #   links:
  #     - main_credit
  #     - replica_credit
  #     - cache
  #   depends_on:
  #     - main_credit
  #     - replica_credit
  #     - cache

  messageapp:
    image: cabify/backend-bootcamp-messageapp
    ports:
      - "3000:3000"

  main_credit:
    image: mongo
    volumes:
      - ./creditMicroservice/data/db:/credit/data/db
    ports:
      - 27017:27017
    command:
      - '--logpath'
      - '/var/log/mongodb/main_credit.log'

  replica_credit:
    image: mongo
    command:
      - '--logpath'
      - '/var/log/mongodb/replica_credit.log'
    volumes:
      - ./creditMicroservice/data/replica:/credit/data/replica
    ports:
      - 27018:27017

  main_message:
    image: mongo
    command:
      - '--logpath'
      - '/var/log/mongodb/main_message.log'
    volumes:
      - ./messageMicroservice/data/db:/message/data/db
    ports:
      - 27027:27017
  replica_message:
    image: mongo
    command:

      - '--logpath'
      - '/var/log/mongodb/replica_message.log'
    volumes:
      - ./messageMicroservice/data/replica:/message/data/replica
    ports:
      - 27028:27017

  cache:
    image: redis
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:cache:6379
    ports:
      - "8081:8081"
